"""add_cloud_pricing_table

Revision ID: bde05dbdad35
Revises: 
Create Date: 2026-02-21 23:42:34.370909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bde05dbdad35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_pricing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor', sa.String(length=16), nullable=False),
    sa.Column('service_name', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('sku_id', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('instance_type', sa.Text(), nullable=True),
    sa.Column('operating_system', sa.Text(), nullable=True),
    sa.Column('price_per_unit', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('price_per_hour', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_api', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor', 'sku_id', 'source_api', name='uq_pricing_vendor_sku_source')
    )
    op.create_index(op.f('ix_cloud_pricing_category'), 'cloud_pricing', ['category'], unique=False)
    op.create_index(op.f('ix_cloud_pricing_instance_type'), 'cloud_pricing', ['instance_type'], unique=False)
    op.create_index(op.f('ix_cloud_pricing_region'), 'cloud_pricing', ['region'], unique=False)
    op.create_index(op.f('ix_cloud_pricing_service_name'), 'cloud_pricing', ['service_name'], unique=False)
    op.create_index(op.f('ix_cloud_pricing_vendor'), 'cloud_pricing', ['vendor'], unique=False)
    op.add_column('invoices', sa.Column('invoice_number', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invoices', sa.Column('vendor_name', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('vendor_address', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('client_name', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('client_address', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('subtotal', sa.Numeric(), nullable=True))
    op.add_column('invoices', sa.Column('tax', sa.Numeric(), nullable=True))
    op.add_column('invoices', sa.Column('total', sa.Numeric(), nullable=True))
    op.add_column('invoices', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('vendors', sa.Column('vendor_address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'vendor_address')
    op.drop_column('invoices', 'currency')
    op.drop_column('invoices', 'total')
    op.drop_column('invoices', 'tax')
    op.drop_column('invoices', 'subtotal')
    op.drop_column('invoices', 'client_address')
    op.drop_column('invoices', 'client_name')
    op.drop_column('invoices', 'vendor_address')
    op.drop_column('invoices', 'vendor_name')
    op.drop_column('invoices', 'due_date')
    op.drop_column('invoices', 'invoice_number')
    op.drop_index(op.f('ix_cloud_pricing_vendor'), table_name='cloud_pricing')
    op.drop_index(op.f('ix_cloud_pricing_service_name'), table_name='cloud_pricing')
    op.drop_index(op.f('ix_cloud_pricing_region'), table_name='cloud_pricing')
    op.drop_index(op.f('ix_cloud_pricing_instance_type'), table_name='cloud_pricing')
    op.drop_index(op.f('ix_cloud_pricing_category'), table_name='cloud_pricing')
    op.drop_table('cloud_pricing')
    # ### end Alembic commands ###
